

import BootstrapActivation from '@/components/BootstrapActivation';
import Footer from '@/components/nav/Footer';
import Header from '@/components/nav/Header';
import Context from '@/states/contexts/Contexts';
import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] });


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Context>
          <Header />

          <div className="container">
            <main role="main" className="container-row">
              {children}
            </main>
          </div>

          <ToastContainer />
          <Footer />
          <BootstrapActivation />
        </Context>
      </body>
    </html>
  );
}
